version: '3'
services:
  gin:
    image: golang:rc
    volumes:
      - ${PWD}:/go/src/local/gin
    ports:
      - 8181:8080
    working_dir: /go/src/local/gin
    command: ["sleep", "inf"]
  mongo:
    image: mongo:5.0.5
    restart: always
    ports:
     - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  jeager:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
  redis:
    image: redis:6.2.6
    ports:
      - 6379:6379
  redisinsight:
    image: redislabs/redisinsight:1.11.0
    ports:
      - 8001:8001
volumes:
  elasticsearch: